In [3]:
import torch
import numpy as np

In [4]:
numpy_tensor = np.random.randn(10,20)
print(numpy_tensor)

[[ 1.13014307  1.87280382  1.32946794 -1.05431245 -1.01825409  0.38830203
   0.83693604 -1.01114038 -2.66400835 -1.30188531 -1.21777888 -0.4029933
   1.08167107 -0.05684794 -0.65535782 -0.55033111  0.15614502 -1.84571774
  -0.24662116 -0.08572743]
 [ 0.06471182 -0.09191587  0.6399285  -0.41053438  1.60539723 -0.13117459
   0.38136257 -0.2392933  -1.21913196  1.00664046  0.21744253 -0.02836981
  -1.014682    0.90750833 -0.08177634  0.24236671  1.01773458 -1.20913131
  -0.07580951 -0.27286565]
 [ 0.81153884 -1.20165626 -1.4948236   0.46247701  0.51629226  1.93529217
  -0.11510537 -0.4637316   1.61516823 -1.14614614  0.74804222 -0.7243825
   0.00740719  1.20799059 -1.00796501  0.67598804  1.3093062   0.06784836
   1.7849049   0.52760982]
 [-0.99358622  1.39569606 -0.66386299 -0.72909762  1.29307071  0.65087193
  -0.55347233 -0.6302226   0.1616248  -1.32584584 -0.1727458   1.40080665
   0.92418401  0.30274952  0.61079878  0.88279328  0.14082279  0.13999833
   0.75273413 -0.30397182]
 [-0.7

In [5]:
pytorch_tensor1 = torch.Tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)
print(pytorch_tensor1)
print(pytorch_tensor2)

tensor([[ 1.1301,  1.8728,  1.3295, -1.0543, -1.0183,  0.3883,  0.8369, -1.0111,
         -2.6640, -1.3019, -1.2178, -0.4030,  1.0817, -0.0568, -0.6554, -0.5503,
          0.1561, -1.8457, -0.2466, -0.0857],
        [ 0.0647, -0.0919,  0.6399, -0.4105,  1.6054, -0.1312,  0.3814, -0.2393,
         -1.2191,  1.0066,  0.2174, -0.0284, -1.0147,  0.9075, -0.0818,  0.2424,
          1.0177, -1.2091, -0.0758, -0.2729],
        [ 0.8115, -1.2017, -1.4948,  0.4625,  0.5163,  1.9353, -0.1151, -0.4637,
          1.6152, -1.1461,  0.7480, -0.7244,  0.0074,  1.2080, -1.0080,  0.6760,
          1.3093,  0.0678,  1.7849,  0.5276],
        [-0.9936,  1.3957, -0.6639, -0.7291,  1.2931,  0.6509, -0.5535, -0.6302,
          0.1616, -1.3258, -0.1727,  1.4008,  0.9242,  0.3027,  0.6108,  0.8828,
          0.1408,  0.1400,  0.7527, -0.3040],
        [-0.7107,  0.3254, -1.6529,  1.6453, -1.1864, -0.4099,  0.1429, -1.3286,
          0.0954,  0.7777, -1.2166,  0.4291, -0.3640, -0.3011,  0.7908,  0.3202,
      

In [6]:
#numpy_array = pytorch_tensor1.numpy()
numpy_array = pytorch_tensor1.cpu().numpy
print(numpy_array)

<built-in method numpy of Tensor object at 0x00000249AA23C2D0>


In [7]:
dtype = torch.cuda.FloatTensor
gpu_tensor = torch.randn(10,20).type(dtype)

gpu_tensor = torch.randn(10,20).cuda(0)
print(gpu_tensor)

tensor([[-5.1561e-01, -2.9571e-01, -1.1934e-01, -8.8475e-01,  8.4611e-01,
         -8.7534e-01, -8.6577e-01,  3.2711e-01,  9.7269e-01, -3.0060e-01,
         -7.1201e-01,  7.4059e-01,  6.4651e-01, -2.9847e-01,  5.9498e-01,
         -2.7161e-01,  9.7207e-01, -6.1627e-01, -1.2126e+00,  7.1875e-01],
        [ 9.5625e-01,  1.1830e-01,  1.5337e-03, -3.6109e-01, -9.7177e-01,
          2.4711e-01, -8.7275e-01,  7.5538e-01,  1.4304e+00, -4.5218e-01,
         -1.2133e+00,  6.6115e-01, -1.1303e+00,  8.1404e-01,  1.4346e+00,
         -7.3480e-01, -3.7777e-02, -6.4663e-01,  1.4310e-01,  1.9729e+00],
        [-1.1081e+00,  9.6602e-01, -2.0051e-01,  1.0337e+00,  1.3139e+00,
         -2.7145e-02, -1.5833e+00, -8.2821e-01, -1.3817e+00, -8.8103e-02,
          5.1659e-01, -1.0312e+00, -1.5915e-01,  3.7468e-01, -5.8714e-01,
          5.4786e-01, -2.1325e-01,  7.7495e-01, -7.7106e-01,  1.9135e-01],
        [ 1.0400e+00,  6.9891e-01,  1.7676e+00, -8.8829e-01,  2.0824e+00,
          7.3799e-01,  8.9455e-01, 

In [8]:
cpu_tensor = gpu_tensor.cpu()

In [9]:
print(pytorch_tensor1.shape)
print(pytorch_tensor1.size())
print(pytorch_tensor1.type())
print(pytorch_tensor1.dim())
print(pytorch_tensor1.numel())

torch.Size([10, 20])
torch.Size([10, 20])
torch.FloatTensor
2
200


In [10]:
extensor = torch.randn(3,2).type(torch.float64)
exnum = extensor.numpy()
print(exnum.size)
print(exnum.dtype)

6
float64


In [11]:
x = torch.ones(2,2)
print(x)
print(x.type())
x = x.long()
print(x)
print(x.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor
tensor([[1, 1],
        [1, 1]])
torch.LongTensor


In [12]:
x = torch.randn(4,3)
print(x)
max_value, max_idx = torch.max(x,dim=1)
print(max_value)
print(max_idx)
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([[ 0.3569, -1.6957,  1.2486],
        [ 0.4098, -0.5826,  1.3379],
        [ 0.8591, -0.4577, -1.5249],
        [-0.2546,  0.8924,  0.0350]])
tensor([1.2486, 1.3379, 0.8591, 0.8924])
tensor([2, 2, 0, 1])
tensor([-0.0901,  1.1652, -1.1234,  0.6728])


In [13]:
print(x.shape)
x = x.unsqueeze(0)
print(x.shape)

x = x.unsqueeze(1)
print(x.shape)

x = x.squeeze()
print(x.shape)

torch.Size([4, 3])
torch.Size([1, 4, 3])
torch.Size([1, 1, 4, 3])
torch.Size([4, 3])


In [14]:
x = torch.randn(3,4,5)
print(x.shape)
print(x)

x = x.permute(1,0,2)
print(x.shape)
print(x)

x = x.transpose(0,2)
print(x.shape)
print(x)

torch.Size([3, 4, 5])
tensor([[[ 0.4235, -0.5452, -1.6099, -0.3338, -3.2150],
         [-0.5779,  0.0346, -0.3393,  0.3121,  2.3220],
         [ 0.5269, -0.2367, -0.4460, -0.1018,  0.5009],
         [-1.7747,  0.3236, -0.9831,  0.3882, -1.5509]],

        [[ 0.4125, -0.8125, -0.2998, -1.3202, -0.8700],
         [-1.1355, -0.6996,  1.1507, -1.6311, -0.9679],
         [ 0.7126,  1.3749, -0.6690, -0.3909, -2.5295],
         [-0.0376, -0.0528, -0.2766,  1.2918,  1.2870]],

        [[-0.0239,  1.1436,  0.5320, -0.7090,  0.3988],
         [ 0.3143,  0.1251,  2.3072, -1.9611, -0.0881],
         [-0.2792,  1.0469,  1.4207, -1.1859, -1.3375],
         [ 0.7529, -0.1741, -0.3661,  0.1573,  0.2894]]])
torch.Size([4, 3, 5])
tensor([[[ 0.4235, -0.5452, -1.6099, -0.3338, -3.2150],
         [ 0.4125, -0.8125, -0.2998, -1.3202, -0.8700],
         [-0.0239,  1.1436,  0.5320, -0.7090,  0.3988]],

        [[-0.5779,  0.0346, -0.3393,  0.3121,  2.3220],
         [-1.1355, -0.6996,  1.1507, -1.6311, -0.967

In [15]:
x = torch.randn(3,4,5)
print(x.shape)

x = x.view(-1,5)
print(x.shape)

x = x.view(3,20)
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


In [16]:
x = torch.randn(3,4)
y = torch.randn(3,4)
z = x + y
print(z)

tensor([[-0.3956, -0.1827, -1.1578, -1.5200],
        [ 0.9298,  0.4857,  1.1097, -0.1711],
        [ 1.6417,  1.9248, -1.6685,  0.8304]])


In [17]:
x = torch.ones(3,3)
x.unsqueeze_(0)
print(x.shape)
x.transpose_(1,0)
print(x.shape)

torch.Size([1, 3, 3])
torch.Size([3, 1, 3])


In [18]:
x = torch.ones(3,3)
y = torch.ones(3,3)

print(x)
x.add_(y)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [19]:
x = torch.ones(4,4).float()
print(x)
x[1:3,1:3] = 2
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 2., 2., 1.],
        [1., 2., 2., 1.],
        [1., 1., 1., 1.]])
