In [10]:
import torch
from torch.autograd import Variable
import numpy as np

In [2]:
x_tensor = torch.randn(10,5)
y_tensor = torch.randn(10,5)

x = Variable(x_tensor, requires_grad=True)

y = Variable(y_tensor, requires_grad=True)

In [4]:
z = torch.sum(x + y)
print(z.data)
print(z.grad_fn)

tensor(3.2043)


In [5]:
z.backward()

print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [11]:
import matplotlib.pyplot as plt
x = np.arange(-3,3.01,0,1)
y = x ** 2
plt.plot(x,y)
plt.plot(2,4,'ro')
plt.show()

TypeError: data type not understood

In [13]:
x = Variable(torch.FloatTensor([2]), requires_grad=True)
y = x ** 2
y.backward()
print(x.grad)

tensor([4.])
