In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = x + 2
z = y ** 2 + 3
print(z)

tensor([28.], grad_fn=<AddBackward>)


In [3]:
z.backward()
print(x.grad)
print(y.grad)

tensor([10.])
None


In [5]:
x = Variable(torch.randn(10,20), requires_grad=True)
y = Variable(torch.randn(10,5), requires_grad=True)
w = Variable(torch.randn(20,5), requires_grad=True)

out = torch.mean(y - torch.matmul(x,w))
out.backward()

In [8]:
print(out)
print(w)
print("-------------------------------------------------")
print(x.grad)
print("-------------------------------------------------")
print(y.grad)

tensor(-1.5851, grad_fn=<MeanBackward1>)
tensor([[-0.2525,  1.2414, -1.8201,  1.0864,  0.5672],
        [-0.5395,  1.2288,  1.5083,  1.9086,  0.4939],
        [-0.6686,  1.8864, -1.4489, -0.9850, -0.5724],
        [ 0.6046, -0.6563, -1.1607,  1.7150, -0.6291],
        [-0.3577, -1.2306,  0.1984, -0.1651, -1.3576],
        [-0.9312, -1.8042, -0.1648,  1.6673, -0.7254],
        [-1.2471,  0.2777,  1.6130,  1.0415,  1.9120],
        [ 0.2783, -0.2626, -0.2481,  0.6003, -1.0160],
        [-0.3646, -0.2908, -0.3929,  1.5981,  1.8916],
        [-0.5174,  0.3501,  0.3844,  0.3526,  1.6261],
        [ 1.5008,  1.1453, -0.3024,  1.2428,  1.8213],
        [-1.3360,  1.6648,  0.1324,  0.7685,  1.2900],
        [-0.7460,  0.9854, -2.0713,  0.1529, -1.8793],
        [ 1.2636, -0.6143,  0.8207, -0.2635,  0.6034],
        [ 0.3322,  0.9147,  0.8122,  0.4643, -0.4610],
        [-1.5785,  1.8645, -0.0624,  0.8085, -0.1897],
        [ 0.1966,  1.6775,  0.0120,  0.4063, -0.2157],
        [-1.4671,  1.247

In [7]:
print(1/50)

0.02


In [16]:
m = Variable(torch.FloatTensor([[2,3]]), requires_grad=True)
n = Variable(torch.zeros(1,2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [17]:
n[0,0] = m[0,0] ** 2
n[0,1] = m[0,1] ** 3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [19]:
n.backward(torch.ones_like(n))

In [12]:
print(m.grad)

tensor([[ 4., 27.]])


In [24]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y = x * 2 + x ** 2 + 3
print(y)

tensor([18.], grad_fn=<AddBackward>)


In [25]:
y.backward(retain_graph=True)

In [26]:
print(x.grad)

tensor([8.])


In [27]:
############################################
x = Variable(torch.FloatTensor([2,3]), requires_grad=True)
k = Variable(torch.zeros([2]))
k[0] = x[0] ** 2 + 3 * x[1]
k[1] = x[0] * 2 + x[1] ** 2

In [28]:
j = torch.zeros(2,2)

In [29]:
k.backward(torch.FloatTensor([1,0]), retain_graph=True)
j[0] = x.grad.data

x.grad.data.zero_()

k.backward(torch.FloatTensor([0,1]))
j[1] = x.grad.data

print(j)

tensor([[4., 3.],
        [2., 6.]])
