In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = x + 2
z = y ** 2 + 3
print(z)

tensor([28.], grad_fn=<AddBackward0>)


In [3]:
z.backward()
print(x.grad)
print(y.grad)

tensor([10.])
None


In [4]:
x = Variable(torch.randn(10,20), requires_grad=True)
y = Variable(torch.randn(10,5), requires_grad=True)
w = Variable(torch.randn(20,5), requires_grad=True)

out = torch.mean(y - torch.matmul(x,w))
out.backward()

In [5]:
print(out)
print(w)
print("-------------------------------------------------")
print(x.grad)
print("-------------------------------------------------")
print(y.grad)

tensor(-0.6770, grad_fn=<MeanBackward0>)
tensor([[-1.1515,  0.9851, -0.4289, -0.1007, -0.2042],
        [ 0.3661, -0.6683,  0.7504,  1.0466,  0.4169],
        [ 2.1582,  0.3418,  1.1201,  0.3889, -0.7893],
        [-0.8802,  1.0367, -1.4780, -0.6447, -0.1093],
        [ 1.0758, -0.4516,  0.0597,  0.2982, -1.4036],
        [-1.2816,  1.5309,  0.5316, -1.4740, -0.1746],
        [ 0.0929,  0.3839,  0.1092,  0.2556, -0.2329],
        [-0.7431,  0.2179, -1.1594, -1.2587, -1.4649],
        [ 0.6931, -0.7682,  0.1756, -0.2580, -1.1667],
        [ 0.8584, -0.5656, -0.5212, -1.8810, -0.4311],
        [ 1.0075,  0.1831,  0.8959,  1.4151, -0.2067],
        [-2.4706, -1.3331, -0.0453, -0.6152, -0.8204],
        [-0.4097, -0.1410,  2.9231,  0.3808,  0.8342],
        [ 0.4871,  0.7377, -1.0266, -1.2563, -1.0410],
        [-0.8723,  0.4107, -0.3253, -0.0375,  0.2994],
        [ 1.6656,  1.2027, -1.2423,  0.0211, -0.2989],
        [ 0.8355,  0.5567,  1.0861,  0.9256,  1.2238],
        [ 1.2010,  0.706

In [6]:
print(1/50)

0.02


In [7]:
m = Variable(torch.FloatTensor([[2,3]]), requires_grad=True)
n = Variable(torch.zeros(1,2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [17]:
n[0,0] = m[0,0] ** 2
n[0,1] = m[0,1] ** 3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [19]:
n.backward(torch.ones_like(n))

In [12]:
print(m.grad)

tensor([[ 4., 27.]])


In [24]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y = x * 2 + x ** 2 + 3
print(y)

tensor([18.], grad_fn=<AddBackward>)


In [25]:
y.backward(retain_graph=True)

In [26]:
print(x.grad)

tensor([8.])


In [27]:
############################################
x = Variable(torch.FloatTensor([2,3]), requires_grad=True)
k = Variable(torch.zeros([2]))
k[0] = x[0] ** 2 + 3 * x[1]
k[1] = x[0] * 2 + x[1] ** 2

In [28]:
j = torch.zeros(2,2)

In [29]:
k.backward(torch.FloatTensor([1,0]), retain_graph=True)
j[0] = x.grad.data

x.grad.data.zero_()

k.backward(torch.FloatTensor([0,1]))
j[1] = x.grad.data

print(j)

tensor([[4., 3.],
        [2., 6.]])
