In [0]:
import torch
from torch.autograd import Variable
from torch import nn

In [0]:
rnn_single = nn.RNNCell(input_size=100, hidden_size=200)

In [6]:
rnn_single.weight_hh

Parameter containing:
tensor([[ 0.0124, -0.0217, -0.0352,  ...,  0.0535,  0.0500,  0.0462],
        [-0.0242,  0.0207,  0.0253,  ...,  0.0124, -0.0500,  0.0430],
        [ 0.0543,  0.0508, -0.0643,  ..., -0.0317,  0.0069, -0.0353],
        ...,
        [ 0.0214, -0.0511, -0.0235,  ...,  0.0484,  0.0165, -0.0655],
        [-0.0624,  0.0038,  0.0456,  ..., -0.0162, -0.0599, -0.0238],
        [-0.0007, -0.0030, -0.0289,  ...,  0.0425,  0.0459,  0.0628]],
       requires_grad=True)

In [0]:
x = Variable(torch.randn(6,5,100))
h_t = Variable(torch.zeros(5,200))

out = []
for i in range(6):
    h_t = rnn_single(x[i], h_t)
    out.append(h_t)

In [0]:
h_t

In [0]:
len(out)

In [0]:
out[0].shape

In [0]:
rnn_seq = nn.RNN(100, 200)

In [0]:
rnn_seq.weight_hh_l0

In [0]:
out, h_t = rnn_seq(x)

In [0]:
h_t

In [0]:
len(out)

In [0]:
h_0 = Variable(torch.randn(1,5,200))

In [0]:
out, h_t = rnn_seq(x,h_0)

In [0]:
h_t

In [0]:
out.shape

In [0]:
lstm_seq = nn.LSTM(50,100,num_layers=2)

In [26]:
lstm_seq.weight_hh_l0

Parameter containing:
tensor([[-0.0895,  0.0978,  0.0296,  ...,  0.0789, -0.0509, -0.0326],
        [ 0.0472, -0.0029, -0.0049,  ..., -0.0498,  0.0013, -0.0482],
        [ 0.0402, -0.0269,  0.0762,  ..., -0.0414,  0.0639,  0.0964],
        ...,
        [-0.0787, -0.0782,  0.0055,  ...,  0.0422, -0.0753, -0.0620],
        [-0.0683, -0.0068, -0.0522,  ..., -0.0844,  0.0812, -0.0197],
        [-0.0439, -0.0912,  0.0483,  ..., -0.0217,  0.0220, -0.0338]],
       requires_grad=True)

In [0]:
lstm_input = Variable(torch.randn(10,3,50))

In [0]:
out, (h, c) = lstm_seq(lstm_input)

In [29]:
h.shape

torch.Size([2, 3, 100])

In [30]:
c.shape

torch.Size([2, 3, 100])

In [31]:
out.shape

torch.Size([10, 3, 100])

In [0]:
h_init = Variable(torch.randn(2,3,100))
c_init = Variable(torch.randn(2,3,100))

In [0]:
out, (h, c) = lstm_seq(lstm_input, (h_init, c_init))

In [35]:
h.shape

torch.Size([2, 3, 100])

In [36]:
out.shape

torch.Size([10, 3, 100])

In [0]:
gru_seq=nn.GRU(10,20)
gru_input = Variable(torch.randn(3, 32, 10))

out, h = gru_seq(gru_input)

In [38]:
gru_seq.weight_hh_l0

Parameter containing:
tensor([[-0.0094, -0.1721,  0.1083,  ..., -0.0084, -0.1938,  0.1430],
        [-0.1603, -0.1052, -0.0701,  ...,  0.1040, -0.0395,  0.0108],
        [ 0.1034,  0.1943,  0.0428,  ...,  0.0729, -0.0097, -0.0715],
        ...,
        [ 0.1669, -0.1386,  0.1705,  ..., -0.0847,  0.1497, -0.1006],
        [ 0.0446,  0.1189,  0.0667,  ...,  0.1295,  0.2213, -0.1951],
        [-0.0219,  0.2067,  0.0382,  ...,  0.1849,  0.1499,  0.1300]],
       requires_grad=True)

In [39]:
h.shape

torch.Size([1, 32, 20])

In [40]:
out.shape

torch.Size([3, 32, 20])

In [41]:
gru_seq

GRU(10, 20)